export const DISHES_REQUEST_START = 'DISHES_REQUEST_START';
export const DISHES_REQUEST_SUCCES = 'DISHES_REQUEST_SUCCES';
export const DISHES_REQUEST_ERROR = 'DISHES_REQUEST_ERROR';

export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';
export const INIT_CART = 'INIT_CART';

export const ORDER_REQUEST_START = 'ORDER_REQUEST_START';
export const ORDER_REQUEST_SUCCES = 'ORDER_REQUEST_SUCCES';
export const ORDER_REQUEST_ERROR = 'ORDER_REQUEST_ERROR';
export const ORDER_INIT = 'ORDER_INIT';
